blank-worlds: 5
mysql:
  username: "username"
  password: "password"
  hostname: "localhost"
  database: "nexus"
cloudtype: "NEXUS"
profile-slots: 4
profile-checkout-after: 30
concurrently-building: 1
base-radius: 90
villager-name: §eGeorge
respawn-range-min: 35
respawn-range-max: 60