name: NexusCore
author: uScoutz
version: 1.0
main: de.uscoutz.nexus.NexusPlugin
api-version: 1.19
commands:
  profile:
  coop:
  stop:
  deletedata:
  checkplayer:
  setlocation:
  profileunload:
  fly:
  joinprofile:
  loadprofile:
    aliases: [spectate]
  addmoney:
  stats:
  adminmode:
    aliases: [admin, am]
loadbefore:
  - NexusSchematic
  - NexusWave